### ISSUE TITLE
Feedback for “Q&A”

### ISSUE THREAD

**Issue by jackyyuwei** [Sanster/lama-cleaner-docs#26]
hello,
 I use windows 1-click installer,
when I run the "win_start.bat",
it reported the below error, 
how to solve it ?
thanks

-----------------------------------------------------------
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.6
- torch: 1.13.1+cu117
- Pillow: 9.5.0
- diffusers: 0.14.0
- transformers: 4.27.4
- opencv-python: 4.7.0.72
- xformers: 0.0.16
- accelerate: 0.18.0
- lama-cleaner: 1.1.2

2023-05-03 23:29:03.330 | INFO     | lama_cleaner.parse_args:parse_args:182 - Loading installer config from D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\win_start.bat\..\installer_config.json
2023-05-03 23:29:12.676 | INFO     | lama_cleaner.server:main:515 - Initialize file manager
Downloading (…)ain/model_index.json: 100%|████████████████████████████████████████████████████| 550/550 [00:00<?, ?B/s]
vae\diffusion_pytorch_model.safetensors not found
Downloading (…)cheduler_config.json: 100%|████████████████████████████████████████████████████| 313/313 [00:00<?, ?B/s]
Downloading (…)_checker/config.json: 100%|████████████████████████████████████████████████| 4.78k/4.78k [00:00<?, ?B/s]
Downloading (…)rocessor_config.json: 100%|████████████████████████████████████████████████████| 342/342 [00:00<?, ?B/s]
Downloading (…)4ae314f8/config.json: 100%|████████████████████████████████████████████████████| 748/748 [00:00<?, ?B/s]
Downloading (…)_encoder/config.json: 100%|████████████████████████████████████████████████████| 617/617 [00:00<?, ?B/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████| 472/472 [00:00<00:00, 478kB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 806/806 [00:00<00:00, 811kB/s]
Downloading (…)4f8/unet/config.json: 100%|████████████████████████████████████████████████████| 748/748 [00:00<?, ?B/s]
Downloading (…)14f8/vae/config.json: 100%|████████████████████████████████████████████████████| 552/552 [00:00<?, ?B/s]
Downloading (…)tokenizer/merges.txt: 100%|███████████████████████████████████████████| 525k/525k [00:01<00:00, 298kB/s]
Downloading (…)tokenizer/vocab.json: 100%|█████████████████████████████████████████| 1.06M/1.06M [00:03<00:00, 352kB/s]
Downloading (…)on_pytorch_model.bin: 100%|███████████████████████████████████████████| 335M/335M [23:32<00:00, 237kB/s]
Downloading pytorch_model.bin: 100%|█████████████████████████████████████████████████| 492M/492M [31:24<00:00, 261kB/s]]
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████| 1.22G/1.22G [35:14<00:00, 575kB/s]]
Downloading (…)on_pytorch_model.bin: 100%|███████████████████████████████████████| 3.44G/3.44G [1:01:51<00:00, 926kB/s]
Fetching 16 files: 100%|████████████████████████████████████████████████████████████| 16/16 [1:01:55<00:00, 232.22s/it]]
D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
flaskwebgui - [INFO] - Opening browser at http://127.0.0.1:8080
Exception in thread Thread-2 (start_webserver):
Traceback (most recent call last):
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flaskwebgui.py", line 234, in start_flask
    import waitress
ModuleNotFoundError: No module named 'waitress'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flaskwebgui.py", line 210, in start_webserver
    self.webserver_dispacher[self.start_server]()
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flaskwebgui.py", line 237, in start_flask
    self.app.run(host=self.host, port=self.port)
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flask\app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\werkzeug\serving.py", line 1052, in run_simple
    inner()
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\werkzeug\serving.py", line 996, in inner
    srv = make_server(
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\werkzeug\serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\werkzeug\serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\http\server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "D:\Tool\lama  cleaner\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。
flaskwebgui - [INFO] - App closed
flaskwebgui - [INFO] - Closing connections...
请按任意键继续. . .

**Comment by Sanster** [comment]
默认是在 8080 端口启动，可能已经被占用了，可以换一个试下，比如  4242
