### ISSUE TITLE
Feedback for “Windows 1click Installer” : Can't install it

### ISSUE THREAD

**Issue by dispather** [Sanster/lama-cleaner-docs#37]
I can`t install this. I once install a lama cleaner using “Windows 1click Installer” but by my mistake, I moved the installed lama cleaner folder and I found it is not working anymore. So, I deleted this folder and unziped “Windows 1click Installer” file and install new.
 As instruction, I double clicked "win_config.bat" and there was some errors but web pages was appears good. 
 After save configurations, I doble clicked "win_start.bat" but it is show error message very quick.
 This is it.
---------------------------------------------- 
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.6
- torch: 2.0.1
- torchvision: 0.15.2
- Pillow: 10.0.0
- diffusers: 0.16.1
- transformers: 4.27.4
- opencv-python: 4.8.0.74
- xformers: 0.0.16
- accelerate: N/A
- lama-cleaner: 1.2.2
- rembg: 2.0.50
- realesrgan: 0.3.0
- gfpgan: 1.3.8

2023-07-14 13:32:34.408 | INFO     | lama_cleaner.parse_args:parse_args:193 - Loading installer config from C:\Users\johnber\Downloads\Compressed\lama-cleaner\win_start.bat\..\installer_config.json
Traceback (most recent call last):
  File "C:\Users\johnber\Downloads\Compressed\lama-cleaner\installer\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\johnber\Downloads\Compressed\lama-cleaner\installer\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnber\Downloads\Compressed\lama-cleaner\installer\Scripts\lama-cleaner.exe\__main__.py", line 7, in <module>
  File "C:\Users\johnber\Downloads\Compressed\lama-cleaner\installer\lib\site-packages\lama_cleaner\__init__.py", line 13, in entry_point
    args = parse_args()
  File "C:\Users\johnber\Downloads\Compressed\lama-cleaner\installer\lib\site-packages\lama_cleaner\parse_args.py", line 206, in parse_args
    import torch
  File "C:\Users\johnber\Downloads\Compressed\lama-cleaner\installer\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure was not found. Error loading "C:\Users\johnber\Downloads\Compressed\lama-cleaner\installer\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.
Press any key to continue . . .
----------------------------------------------

How can I solve this problem? I attach screen shots that shown during execute "win_config.bat", too.
![2023-07-14 12 39 54](https://github.com/Sanster/lama-cleaner-docs/assets/62810211/f7b076ab-1a59-4737-976b-285a7d0e2f05)

**Comment by dispather** [comment]
I solve this problem with "--no-cache" option to setup torch 1.13.1, instead 2.0.1.
